name: 'Trigger ADO Pipeline'
description: 'Triggers an Azure DevOps pipeline from a GitHub Action'
inputs:
  ado_org:
    required: false
    default: 'hmcts-cpp'
    description: "Azure DevOps organisation name"
  ado_project:
    required: false
    default: 'cpp-apps'
    description: "Azure DevOps project name"
  pipeline_id:
    required: true
    description: "ID of the Azure DevOps pipeline to trigger"
  ado_pat:
    required: true
    description: "Azure DevOps Personal Access Token (PAT) used for authentication"
  template_parameters:
    required: true
    description: "JSON string of key-value pairs to pass as template parameters to the pipeline"
  ref_name:
    required: false
    default: 'refs/heads/main'
    description: 'Git reference (branch) to use in the triggered pipeline'
  api_version:
    required: false
    default: '7.0'
    description: "API version to use for Azure DevOps pipeline trigger"
  release_candidate:
    required: false
    default: false
    description: "Indicates whether the artefact is considered a release candidate."
runs:
  using: "composite"
  steps:
    - run: python3 ${{ github.action_path }}/trigger_pipeline.py
      shell: bash
      env:
        INPUT_ADO_ORG: ${{ inputs.ado_org }}
        INPUT_ADO_PROJECT: ${{ inputs.ado_project }}
        INPUT_PIPELINE_ID: ${{ inputs.pipeline_id }}
        INPUT_ADO_PAT: ${{ inputs.ado_pat }}
        INPUT_TEMPLATE_PARAMETERS: ${{ inputs.template_parameters }}
        INPUT_REF_NAME: ${{ inputs.ref_name }}
        INPUT_API_VERSION: ${{ inputs.api_version }}
        INPUT_RELEASE_CANDIDATE: ${{ inputs.release_candidate }}
